### ISSUE TITLE
Can't launch legit

### ISSUE THREAD

**Issue by riceharvest** [Nuclearistt/TEKLauncher#6] opened 2022-04-06 22:02 UTC
It worked in the previous version, sometimes I had to re-launch te TekLauncher but it did end up working.
Now It only launches with the TekInjector, but owning the legit game and playing on my own un-official servers, I need to launch the legit game.

![TEKLauncher_9KmMUURlGj](https://user-images.githubusercontent.com/79027318/162079274-79526bbf-6d8d-4e3a-a5b5-c3642eb5dfdb.png)
![steam_yxWokLCOaD](https://user-images.githubusercontent.com/79027318/162079339-a247fa14-53e6-46d4-ae31-4314f5bf5a1d.png)

**Comment by Nuclearistt** [comment] 2022-04-07 07:06
I'm aware of this issue, it's caused by case-sensibility of the check that shouldn't be there and it will be fixed in next update. But you always have the option to run it via Steam itself, like there would be no difference

**Closed** 2022-04-10 15:11 UTC
Labels: bug
